Repository thoth-station/moldavite-api, pull requests merged in 2021-08, with the labels that each got.

#4 Fix typing errors
  Pipfile
  Pipfile.lock
  moldavite/api_v1.py
  moldavite/entrypoint.py
Labels: size/L

#7 Add mypy.ini file
  mypy.ini
Labels: approved, ok-to-test, size/S

#11 openshift pipelines which will take care of meteor
  openshift/moldavite-jupyterbook-build.yaml
Labels: approved, size/M

#12 Incorporate pipelines into the workflow
  openshift/moldavite-jupyterbook-build.yaml
Labels: size/M

#18 Resources required for the moldavite deployment
  .pre-commit-config.yaml
  moldavite/api_v1.py
  moldavite/entrypoint.py
  openapi/openapi.yaml
  openshift/argo-deployments.yaml
  openshift/argo-imagestreams.yaml
  openshift/argo-management.yaml
  openshift/argo-ui-controller.yaml
  openshift/argo-workflow-controller.yaml
  openshift/kustomization.yaml
  openshift/moldavite-configmap.yaml
  openshift/moldavite-imagestream.yaml
  openshift/moldavite-jupyterbook-build.yaml
  openshift/moldavite-jupyterhub-build.yaml
  openshift/moldavite-rbac.yaml
  openshift/moldavite-route.yaml
  openshift/moldavite-service.yaml
  openshift/moldavite.yaml
Labels: approved, size/XXL

#19 Add configmap for workflow-controller
  openshift/argo-workflow-controller-configmap.yaml
  openshift/kustomization.yaml
Labels: approved, size/S

#20 Remove endpoints exposing build logs
  moldavite/api_v1.py
  openapi/openapi.yaml
Labels: approved, size/M

#22 Add Harshad to OWNERS
  OWNERS
Labels: approved, size/XS
